
project_id = "rvduyqzejmmwwixtuevy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[functions.get-spin-reward]
verify_jwt = true

[functions.admin-get-users]
verify_jwt = true
